import { getAllBookings, getWeeklyConversionMetrics, getFirestoreDb } from './bookingService';
import { getAlerts } from './alertService';
import { getProvidersOverview } from './providerCommunicationService';
import { getNativeEngineStatus, getNativeAutomationLogs } from './nativeAutomationEngine';
import { getSelfDevelopmentOverview } from './selfDevelopmentEngine';
import { AGENT_IDENTITIES } from './agentKnowledgeFabric';
import { listSkillVersions } from './skillGenome';
import { getEmailOperationsSnapshot } from './emailOperationsAgent';
const money=(v:any)=>Number.isFinite(Number(v))?Math.round(Number(v)*100)/100:0;
export async function getAdminControlCenterSnapshot(){
 const [bookings,alerts,conversion,selfDevelopment]=await Promise.all([getAllBookings(),getAlerts({resolved:false}),getWeeklyConversionMetrics().catch(()=>null),getSelfDevelopmentOverview().catch(()=>null)]);
 const providers:any=getProvidersOverview(),now=Date.now();
 const confirmed=bookings.filter((b:any)=>['confirmada','confirmed','completada','completed'].includes(String(b.status||'').toLowerCase()));
 const pending=bookings.filter((b:any)=>['pending','pendiente','pendiente_pago','hold'].includes(String(b.status||b.paymentStatus||'').toLowerCase()));
 const failed=bookings.filter((b:any)=>['rejected','rechazada','cancelled','cancelada','error'].includes(String(b.status||'').toLowerCase()));
 const upcoming=bookings.filter((b:any)=>{const t=new Date(String(b.date||'')+'T'+String(b.time||'00:00:00')).getTime();return Number.isFinite(t)&&t>=now&&t<=now+72*60*60*1000;});
 const revenue=confirmed.reduce((s:number,b:any)=>s+money(b.totalUSD),0),db=getFirestoreDb();let journeys:any[]=[],inbox:any[]=[],evaluations:any[]=[],memories:any[]=[];
 if(db){const [j,i,e,m]=await Promise.all([db.collection('traveler_journeys').orderBy('updatedAt','desc').limit(100).get().catch(()=>({docs:[]} as any)),db.collection('provider_inbox_events').orderBy('processedAt','desc').limit(30).get().catch(()=>({docs:[]} as any)),db.collection('ai_evaluations').orderBy('createdAt','desc').limit(30).get().catch(()=>({docs:[]} as any)),db.collection('agent_memory').limit(100).get().catch(()=>({docs:[]} as any))]);journeys=j.docs||[];inbox=i.docs||[];evaluations=e.docs||[];memories=m.docs||[];}
 const journeyData=journeys.map((d:any)=>({id:d.id,...d.data()})),pipeline={discovery:0,verification:0,readyToQuote:0,recovery:0,total:journeyData.length};
 journeyData.forEach((j:any)=>{const s=String(j.sales?.stage||j.status||'').toUpperCase();if(s==='DISCOVERY'||s==='PLANNING')pipeline.discovery++;else if(s==='VERIFICATION'||s==='VERIFICATION_COMPLETE')pipeline.verification++;else if(s==='READY_TO_QUOTE')pipeline.readyToQuote++;else if(s==='RECOVERY')pipeline.recovery++;});
 return{generatedAt:new Date().toISOString(),business:{totalBookings:bookings.length,confirmedBookings:confirmed.length,pendingBookings:pending.length,failedOrCancelled:failed.length,upcoming72h:upcoming.length,revenueUSD:revenue,averageBookingUSD:confirmed.length?money(revenue/confirmed.length):0},conversion,alerts:{unresolved:alerts.length,critical:alerts.filter((a:any)=>a.severity==='critical').length,warning:alerts.filter((a:any)=>a.severity==='warning').length,recent:alerts.slice(0,20)},agents:AGENT_IDENTITIES.map((a:any)=>({id:a.id,mission:a.mission,capabilities:a.canRead||[],writableDomains:a.canWrite||[],escalation:a.escalation||[]})),automation:{engine:getNativeEngineStatus(),recentLogs:getNativeAutomationLogs(50),providerInbox:{mode:'Gmail OAuth + native cron every minute',configured:Boolean(process.env.GMAIL_CLIENT_ID&&process.env.GMAIL_CLIENT_SECRET&&process.env.GMAIL_REFRESH_TOKEN)},emailOperations:await getEmailOperationsSnapshot(20)},providers:{total:providers.totalProviders,active:providers.activeProviders,activeOrders:providers.activeOrdersCount,list:(providers.providers||[]).slice(0,30).map((p:any)=>({id:p.id,name:p.name,region:p.region,status:p.status,activeOrdersCount:p.activeOrdersCount,slaTargetMinutes:p.slaTargetMinutes,averageResponseMinutes:p.averageResponseMinutes,acceptanceRate:p.acceptanceRate}))},evolution:{selfDevelopment:selfDevelopment||{enabled:false},skills:listSkillVersions().map((s:any)=>({id:s.id,version:s.version,lifecycle:s.lifecycle,exposure:s.exposure,routingScore:s.routingScore})),recentEvaluations:evaluations.map((d:any)=>({id:d.id,...d.data()})).slice(0,20)},documents:{journeys:journeys.length,inboxEvents:inbox.length,evaluations:evaluations.length,memories:memories.length},journeyPipeline:pipeline,journeyRecent:journeyData.slice(0,20).map((j:any)=>({id:j.journeyId||j.id,updatedAt:j.updatedAt,stage:j.sales?.stage||j.status||'unknown',nextAction:j.sales?.nextAction||'',travelers:j.traveler?.travelers||0,profile:j.traveler?.profile||'',regions:j.planning?.regions||[]})),providerInbox:inbox.map((d:any)=>({id:d.id,...d.data()})).slice(0,30)};
}