import React,{useEffect,useState} from 'react';
import {auth} from '../firebase';
import {Brain,CalendarDays,Compass,ShieldCheck,Sparkles,UserRound} from 'lucide-react';
export const AccountDashboardPage:React.FC<{language:'es'|'en'}>=({language})=>{
 const es=language==='es';const [data,setData]=useState<any>(null);const [error,setError]=useState('');const [loading,setLoading]=useState(true);
 useEffect(()=>{let active=true;(async()=>{try{const user=auth.currentUser;if(!user)throw new Error(es?'Inicia sesión para abrir tu espacio personal.':'Sign in to open your personal space.');const token=await user.getIdToken();const r=await fetch('/api/me/ai-profile',{headers:{Authorization:'Bearer '+token}});const j=await r.json();if(!r.ok)throw new Error(j?.error||'No se pudo cargar el perfil.');if(active)setData(j);}catch(e:any){if(active)setError(e?.message||'Error');}finally{if(active)setLoading(false);}})();return()=>{active=false};},[es]);
 if(loading)return <main className="min-h-[70vh] flex items-center justify-center text-emerald-300"><Sparkles className="animate-pulse"/></main>;
 if(error)return <main className="max-w-4xl mx-auto px-4 py-16"><div className="rounded-3xl border border-rose-400/20 bg-rose-950/20 p-8 text-rose-100">{error}</div></main>;
 const p=data?.profile||{};const m=data?.memory||{};const staff=p.role==='admin'||p.role==='operator';
 return <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8 space-y-6">
  <section className="rounded-[32px] border border-emerald-400/20 bg-gradient-to-br from-[#07251a] via-[#04150e] to-[#020906] p-7 shadow-2xl"><div className="flex flex-col md:flex-row md:items-center gap-5">{p.photoURL?<img src={p.photoURL} alt="" className="w-20 h-20 rounded-3xl object-cover border border-emerald-400/30"/>:<div className="w-20 h-20 rounded-3xl bg-emerald-500/10 flex items-center justify-center"><UserRound size={32}/></div>}<div className="flex-1"><div className="text-[10px] uppercase tracking-[.22em] text-emerald-300 font-black">{staff?(es?'Cuenta operativa':'Operations account'):(es?'Tu espacio de viaje':'Your travel space')}</div><h1 className="mt-2 text-3xl md:text-5xl font-black text-white">{p.displayName||p.email||(es?'Viajero':'Traveler')}</h1><p className="mt-2 text-stone-400">{p.email||''}</p></div>{staff&&<div className="inline-flex items-center gap-2 rounded-2xl bg-amber-400/10 border border-amber-400/30 px-4 py-3 text-amber-300 text-sm font-black"><ShieldCheck size={17}/>{p.role==='admin'?'OWNER / ADMIN':'OPERATOR'}</div>}</div></section>
  <section className="grid md:grid-cols-3 gap-4">{[[Brain,es?'Memoria IA':'AI memory',m.lastUpdatedAt?new Date(m.lastUpdatedAt).toLocaleString():'—'],[Compass,es?'Preferencias':'Preferences',m.preferences?.length||0],[CalendarDays,es?'Objetivos activos':'Active goals',m.activeGoals?.length||0]].map(([Icon,title,value]:any)=><div key={title} className="rounded-3xl border border-white/10 bg-white/[.03] p-5"><Icon className="text-emerald-300"/><div className="mt-3 text-xs text-stone-500 uppercase font-black">{title}</div><div className="mt-1 text-lg font-black text-white">{value}</div></div>)}</section>
  <section className="rounded-3xl border border-violet-400/15 bg-[#0a0915] p-6"><div className="flex items-center gap-2"><Brain className="text-violet-300"/><h2 className="text-xl font-black text-white">{es?'Contexto personal de la IA':'AI personal context'}</h2></div><p className="mt-3 text-sm text-stone-400">{m.summary||(es?'Tus preferencias, objetivos y viajes se irán construyendo conforme interactúes con la plataforma.':'Your preferences, goals and trips will build as you use the platform.')}</p><div className="mt-5 flex flex-wrap gap-2">{(m.preferences||[]).map((x:string)=><span key={x} className="rounded-full bg-emerald-400/10 border border-emerald-400/20 px-3 py-1 text-xs text-emerald-200">{x}</span>)}</div></section>
 </main>;
};