import React, { useState } from 'react';
import { Bot, BrainCircuit, CheckCircle2, Code2, History, LockKeyhole, Play, ShieldAlert, Sparkles, Wand2 } from 'lucide-react';
import { Language } from '../types';
import { auth } from '../firebase';

export const AdminAICommandPage: React.FC<{language: Language}> = ({language}) => {
  const es=language==='es'; const [prompt,setPrompt]=useState(''); const [mode,setMode]=useState('analyze'); const [result,setResult]=useState<any>(); const [loading,setLoading]=useState(false); const [error,setError]=useState('');
  const run=async()=>{setLoading(true);setError('');try{const u=auth.currentUser;if(!u)throw new Error(es?'Sesión administrativa requerida.':'Administrative session required.');const token=await u.getIdToken();const r=await fetch('/api/admin/ai-command',{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify({prompt,mode})});const j=await r.json();if(!r.ok)throw new Error(j.error||'AI command failed');setResult(j);}catch(e:any){setError(e.message||'Error')}finally{setLoading(false)}};
  return <div className="max-w-[1500px] mx-auto px-4 py-7 space-y-6">
    <section className="rounded-[32px] border border-violet-400/20 bg-gradient-to-br from-[#160d2b] to-[#030208] p-7"><div className="flex items-center gap-2 text-violet-300 text-[10px] font-black uppercase tracking-[0.22em]"><BrainCircuit size={16}/> {es?'Sala de mando inteligente':'Intelligent command room'}</div><h1 className="mt-2 text-4xl font-black text-white">{es?'Copiloto empresarial IA':'AI business copilot'}</h1><p className="mt-2 text-sm text-stone-300">{es?'Analiza, estudia, propone y prepara cambios; las acciones sensibles requieren aprobación humana.':'Analyze, study, propose and prepare changes; sensitive actions require human approval.'}</p></section>
    <section className="grid xl:grid-cols-3 gap-5"><div className="xl:col-span-2 rounded-3xl border border-white/10 bg-[#0a0a10] p-5"><div className="flex gap-2 mb-4">{[['analyze','Analizar',Sparkles],['propose','Proponer',Wand2],['code','Preparar código',Code2]].map(([v,l,I]:any)=><button key={v} onClick={()=>setMode(v)} className={`rounded-xl px-3 py-2 text-xs font-black ${mode===v?'bg-violet-500 text-white':'bg-white/5 text-stone-400'}`}><I size={14} className="inline mr-1"/>{l}</button>)}</div><textarea value={prompt} onChange={e=>setPrompt(e.target.value)} rows={8} placeholder={es?'Ej.: analiza rentabilidad, proveedores, riesgos y oportunidades y propón acciones...':'Example: analyze profitability, providers, risks and opportunities and propose actions...'} className="w-full rounded-2xl border border-white/10 bg-black/30 p-4 text-sm text-white"/><div className="mt-4 flex justify-end"><button onClick={run} disabled={loading||!prompt.trim()} className="inline-flex items-center gap-2 rounded-xl bg-violet-500 px-5 py-3 text-xs font-black text-white disabled:opacity-50"><Play size={15}/>{loading?'Procesando…':'Ejecutar IA'}</button></div></div>
    <div className="rounded-3xl border border-emerald-400/15 bg-[#07140f] p-5"><div className="flex items-center gap-2"><LockKeyhole className="text-emerald-300" size={18}/><h2 className="font-black text-white">Gobierno humano</h2></div><ul className="mt-4 space-y-3 text-xs text-stone-300"><li><CheckCircle2 className="inline text-emerald-300 mr-2" size={14}/>Firebase + roles administrativos</li><li><CheckCircle2 className="inline text-emerald-300 mr-2" size={14}/>Aprobación antes de cambios sensibles</li><li><CheckCircle2 className="inline text-emerald-300 mr-2" size={14}/>Trazabilidad</li><li><ShieldAlert className="inline text-amber-300 mr-2" size={14}/>Código generado requiere revisión</li></ul></div></section>
    {error&&<div className="rounded-2xl border border-rose-400/20 bg-rose-950/30 p-4 text-sm text-rose-200">{error}</div>}{result&&<section className="rounded-3xl border border-violet-400/20 bg-[#08060d] p-5"><div className="flex items-center gap-2"><Bot className="text-violet-300"/><h2 className="font-black text-white">Resultado</h2></div><pre className="mt-4 whitespace-pre-wrap text-xs leading-6 text-stone-200">{JSON.stringify(result,null,2)}</pre></section>}
  </div>;
};