import React,{useEffect,useState} from 'react';
import {Activity,AlertTriangle,BarChart3,Bot,CheckCircle2,Clock3,Database,Mail,RefreshCw,ShieldCheck,Users,Wallet} from 'lucide-react';
import {Language} from '../types';
import {auth} from '../firebase';

export const AdminControlCenterPage:React.FC<{language:Language}>=({language})=>{
 const es=language==='es';const [data,setData]=useState<any>(null);const [error,setError]=useState('');const [loading,setLoading]=useState(true);
 async function load(){setLoading(true);setError('');try{const user=auth.currentUser;if(!user)throw new Error(es?'Inicia sesión con una cuenta administrativa.':'Sign in with an administrator account.');const token=await user.getIdToken();const r=await fetch('/api/admin/control-center',{headers:{Authorization:'Bearer '+token}});const j=await r.json();if(!r.ok)throw new Error(j.error||'No autorizado');setData(j);}catch(e:any){setError(e?.message||'Error');}finally{setLoading(false);}}
 useEffect(()=>{load();const id=window.setInterval(load,60000);return()=>window.clearInterval(id);},[]);
 const b=data?.business||{},a=data?.alerts||{},p=data?.providers||{},auto=data?.automation||{},pipe=data?.journeyPipeline||{},docs=data?.documents||{};
 const cards=[[BarChart3,b.totalBookings,es?'Reservas':'Bookings'],[CheckCircle2,b.confirmedBookings,es?'Confirmadas':'Confirmed'],[Clock3,b.pendingBookings,es?'Pendientes':'Pending'],[Wallet,'$'+(b.revenueUSD||0),es?'Ventas USD':'Revenue USD'],[Activity,b.upcoming72h,es?'Próximas 72h':'Next 72h'],[AlertTriangle,a.unresolved,es?'Alertas':'Alerts'],[Bot,(data?.agents||[]).length,es?'Agentes':'Agents'],[Database,docs.journeys||0,es?'Viajes':'Journeys']];
 if(error&&!data)return <main className='max-w-6xl mx-auto px-4 py-12'><div className='rounded-3xl border border-rose-400/20 bg-rose-950/20 p-8 text-rose-100'><h1 className='text-3xl font-black'>{es?'Centro de Control':'Control Center'}</h1><p className='mt-3'>{error}</p><button onClick={load} className='mt-5 rounded-xl bg-amber-400 px-4 py-2 font-black text-stone-950'>{es?'Reintentar':'Retry'}</button></div></main>;
 return <main className='max-w-[1500px] mx-auto px-4 sm:px-6 lg:px-8 py-7 space-y-6'>
  <section className='rounded-[32px] border border-amber-400/20 bg-gradient-to-br from-[#071e14] via-[#041711] to-[#020b07] p-7 shadow-2xl'><div className='flex flex-col lg:flex-row lg:items-end lg:justify-between gap-4'><div><div className='flex items-center gap-2 text-amber-300 text-[10px] font-black uppercase tracking-[.22em]'><ShieldCheck size={15}/> {es?'Nivel administrativo':'Administrative level'}</div><h1 className='mt-2 text-3xl md:text-5xl font-black text-white'>{es?'Centro de Control Costa Rica Tours':'Costa Rica Tours Control Center'}</h1><p className='mt-3 max-w-4xl text-sm text-stone-300'>{es?'Ventas, viajeros, proveedores, IA, automatizaciones, fallos y evolución en una sola vista.':'Sales, travelers, providers, AI, automation, failures and evolution in one view.'}</p></div><button onClick={load} disabled={loading} className='inline-flex items-center gap-2 rounded-2xl bg-amber-400 px-4 py-3 font-black text-stone-950'><RefreshCw size={17} className={loading?'animate-spin':''}/>{es?'Actualizar':'Refresh'}</button></div></section>
  <section className='grid grid-cols-2 md:grid-cols-4 xl:grid-cols-8 gap-3'>{cards.map(([Icon,value,label]:any)=><div key={label} className='rounded-2xl border border-emerald-500/15 bg-[#061d14] p-4'><Icon className='text-amber-300' size={18}/><div className='mt-2 text-2xl font-black text-white'>{value??'—'}</div><div className='mt-1 text-[9px] font-black uppercase tracking-wider text-stone-500'>{label}</div></div>)}</section>
  <section className='grid xl:grid-cols-3 gap-5'>
   <div className='xl:col-span-2 rounded-3xl border border-cyan-400/15 bg-[#06141b] p-5'><div className='flex items-center gap-2'><BarChart3 className='text-cyan-300'/><h2 className='font-black text-white'>{es?'Embudo de viajeros':'Traveler funnel'}</h2><span className='ml-auto text-xs text-stone-500'>{pipe.total||0}</span></div><div className='mt-5 grid md:grid-cols-4 gap-3'>{[['Discovery',pipe.discovery],['Verification',pipe.verification],['Ready to quote',pipe.readyToQuote],['Recovery',pipe.recovery]].map(([k,v]:any)=><div key={k} className='rounded-2xl bg-black/20 p-4'><div className='text-xs text-stone-400'>{k}</div><div className='mt-2 text-3xl font-black text-white'>{v||0}</div></div>)}</div><div className='mt-5 rounded-2xl border border-white/5 bg-black/20 p-4'><div className='text-xs font-black text-cyan-200'>{es?'Conversión semanal':'Weekly conversion'}</div><pre className='mt-2 max-h-40 overflow-auto text-[10px] text-stone-400 whitespace-pre-wrap'>{JSON.stringify(data?.conversion||{},null,2)}</pre></div></div>
   <div className='rounded-3xl border border-rose-400/15 bg-[#170b0b] p-5'><div className='flex items-center gap-2'><AlertTriangle className='text-rose-300'/><h2 className='font-black text-white'>{es?'Riesgo operativo':'Operational risk'}</h2></div><div className='mt-5 grid grid-cols-3 gap-2'>{[['critical',a.critical],['warning',a.warning],['all',a.unresolved]].map(([k,v]:any)=><div key={k} className='rounded-xl bg-black/20 p-3 text-center'><div className='text-xl font-black text-white'>{v||0}</div><div className='text-[9px] uppercase text-stone-500'>{k}</div></div>)}</div><div className='mt-4 space-y-2 max-h-72 overflow-auto'>{(a.recent||[]).map((x:any)=><div key={x.id} className='rounded-xl border border-white/5 bg-black/20 p-3'><div className='text-xs font-bold text-white'>{x.title}</div><div className='mt-1 text-[10px] text-stone-400'>{x.message}</div></div>)}{!a.recent?.length&&<p className='text-sm text-stone-500'>{es?'Sin alertas activas.':'No active alerts.'}</p>}</div></div>
  </section>
  <section className='grid xl:grid-cols-2 gap-5'>
   <div className='rounded-3xl border border-violet-400/15 bg-[#0b0a18] p-5'><div className='flex items-center gap-2'><Bot className='text-violet-300'/><h2 className='font-black text-white'>{es?'Fuerza de inteligencias':'AI workforce'}</h2><span className='ml-auto text-xs text-violet-300'>{(data?.agents||[]).length}</span></div><div className='mt-4 grid sm:grid-cols-2 gap-2 max-h-[500px] overflow-auto'>{(data?.agents||[]).map((x:any)=><div key={x.id} className='rounded-2xl border border-white/5 bg-white/[.03] p-3'><div className='flex items-center gap-2'><span className='h-2 w-2 rounded-full bg-emerald-400'/><b className='text-sm text-white'>{x.id}</b></div><p className='mt-1 text-[10px] text-stone-400'>{x.mission}</p><div className='mt-2 text-[9px] text-violet-300'>{(x.capabilities||[]).join(' • ')}</div></div>)}</div></div>
   <div className='rounded-3xl border border-sky-400/15 bg-[#06121b] p-5'><div className='flex items-center gap-2'><Mail className='text-sky-300'/><h2 className='font-black text-white'>{es?'Correo de proveedores':'Provider email agent'}</h2></div><div className='mt-4 rounded-2xl bg-black/20 p-4'><div className='flex justify-between text-xs'><span className='text-stone-400'>Gmail OAuth</span><b className={auto.providerInbox?.configured?'text-emerald-300':'text-amber-300'}>{auto.providerInbox?.configured?'CONFIGURADO':'PENDIENTE'}</b></div><p className='mt-2 text-[10px] text-stone-500'>{es?'El agente revisa la bandeja cada minuto cuando está configurado.':'The agent checks the inbox every minute when configured.'}</p></div><div className='mt-4 max-h-72 overflow-auto space-y-2'>{(data?.providerInbox||[]).map((x:any)=><div key={x.id} className='rounded-xl border border-white/5 bg-black/20 p-3'><b className='text-xs text-white'>{x.status}</b><div className='text-[10px] text-stone-400'>{x.subject||x.orderId||''}</div></div>)}</div></div>
  </section>
  <section className='grid xl:grid-cols-2 gap-5'>
   <div className='rounded-3xl border border-emerald-500/15 bg-[#061d14] p-5'><div className='flex items-center gap-2'><Activity className='text-emerald-300'/><h2 className='font-black text-white'>{es?'Automatización nativa':'Native automation'}</h2></div><div className='mt-4 grid grid-cols-2 sm:grid-cols-4 gap-2'>{[['Exec',auto.engine?.totalExecutions],['Success',(auto.engine?.successRate||0)+'%'],['Latency',(auto.engine?.averageLatencyMs||0)+'ms'],['Workflows',auto.engine?.activeWorkflows]].map(([k,v]:any)=><div key={k} className='rounded-xl bg-black/20 p-3'><div className='text-lg font-black text-white'>{v??0}</div><div className='text-[9px] uppercase text-stone-500'>{k}</div></div>)}</div><div className='mt-4 max-h-64 overflow-auto space-y-2'>{(auto.recentLogs||[]).slice(0,15).map((x:any)=><div key={x.id} className='rounded-xl bg-black/20 p-3'><div className='flex justify-between text-[10px]'><b className={x.status==='error'?'text-rose-300':'text-emerald-300'}>{x.status}</b><span className='text-stone-500'>{x.durationMs}ms</span></div><div className='mt-1 text-xs text-white'>{x.trigger}</div></div>)}</div></div>
   <div className='rounded-3xl border border-amber-400/15 bg-[#171108] p-5'><div className='flex items-center gap-2'><Database className='text-amber-300'/><h2 className='font-black text-white'>{es?'Documentos y proveedores':'Documents & providers'}</h2></div><div className='mt-4 grid grid-cols-2 sm:grid-cols-4 gap-2'>{Object.entries(docs).map(([k,v]:any)=><div key={k} className='rounded-xl bg-black/20 p-3'><div className='text-xl font-black text-white'>{v}</div><div className='text-[9px] uppercase text-stone-500'>{k}</div></div>)}</div><div className='mt-4 space-y-2'>{(p.list||[]).slice(0,12).map((x:any)=><div key={x.id} className='flex items-center justify-between rounded-xl bg-black/20 px-3 py-2'><span className='text-xs font-bold text-white'>{x.name}</span><span className='text-[10px] text-emerald-300'>{x.status} · {x.activeOrdersCount||0}</span></div>)}</div></div>
  </section>
  <section className='rounded-2xl border border-white/10 bg-black/20 p-4 text-[10px] text-stone-500'><Users size={13} className='inline mr-2'/>{es?'Actualización automática cada 60 segundos. Datos operativos sensibles requieren autenticación administrativa.':'Auto-refresh every 60 seconds. Sensitive operational data requires administrator authentication.'} · {data?.generatedAt||'—'}</section>
 </main>;
};