import React,{useState} from 'react';
import {useNavigate} from 'react-router-dom';
import {LogIn,Mail,ShieldCheck,Sparkles} from 'lucide-react';
import {auth,registerWithEmail,signInWithEmail,signInWithGoogle} from '../firebase';

export const LoginPage:React.FC<{language:'es'|'en'}>=({language})=>{
 const es=language==='es';const navigate=useNavigate();const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [mode,setMode]=useState<'login'|'register'>('login');const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{if(mode==='login')await signInWithEmail(email,password);else await registerWithEmail(email,password);navigate('/account');}catch(err:any){setError(err?.message|| (es?'No se pudo autenticar.':'Authentication failed.'));}finally{setBusy(false);}}
 async function google(){setBusy(true);setError('');try{await signInWithGoogle();navigate('/account');}catch(err:any){setError(err?.message||'Google sign-in failed.');}finally{setBusy(false);}}
 return <main className="min-h-[75vh] flex items-center justify-center px-4 py-12"><section className="w-full max-w-md rounded-[32px] border border-emerald-400/20 bg-[#061a12] p-7 shadow-2xl"><div className="text-center"><div className="mx-auto w-14 h-14 rounded-2xl bg-emerald-400/10 flex items-center justify-center"><Sparkles className="text-emerald-300"/></div><h1 className="mt-5 text-3xl font-black text-white">{es?'Tu cuenta Costa Rica Tours':'Your Costa Rica Tours account'}</h1><p className="mt-2 text-sm text-stone-400">{es?'Tus reservas, preferencias y memoria IA quedan asociadas a tu identidad.':'Your bookings, preferences and AI memory stay associated with your identity.'}</p></div><button onClick={google} disabled={busy} className="mt-6 w-full rounded-2xl bg-white text-stone-900 py-3 font-black flex items-center justify-center gap-2"><LogIn size={17}/>{es?'Continuar con Google':'Continue with Google'}</button><div className="my-5 flex items-center gap-3 text-[10px] uppercase tracking-widest text-stone-600"><span className="h-px flex-1 bg-white/10"/>{es?'o correo':'or email'}<span className="h-px flex-1 bg-white/10"/></div><form onSubmit={submit} className="space-y-3"><div><label className="text-xs text-stone-400">{es?'Correo electrónico':'Email'}</label><input value={email} onChange={e=>setEmail(e.target.value)} type="email" required className="mt-1 w-full rounded-xl bg-black/30 border border-white/10 px-3 py-3 text-white outline-none focus:border-emerald-400"/></div><div><label className="text-xs text-stone-400">{es?'Contraseña':'Password'}</label><input value={password} onChange={e=>setPassword(e.target.value)} type="password" minLength={6} required className="mt-1 w-full rounded-xl bg-black/30 border border-white/10 px-3 py-3 text-white outline-none focus:border-emerald-400"/></div>{error&&<div className="rounded-xl bg-rose-950/30 border border-rose-400/20 p-3 text-xs text-rose-200">{error}</div>}<button disabled={busy} className="w-full rounded-2xl bg-emerald-400 text-stone-950 py-3 font-black disabled:opacity-50"><Mail size={16} className="inline mr-2"/>{mode==='login'?(es?'Entrar':'Sign in'):(es?'Crear cuenta':'Create account')}</button></form><button onClick={()=>setMode(mode==='login'?'register':'login')} className="mt-4 w-full text-xs text-emerald-300 hover:text-white">{mode==='login'?(es?'¿No tienes cuenta? Crear una':'No account? Create one'):(es?'Ya tengo cuenta':'I already have an account')}</button><div className="mt-5 flex items-center justify-center gap-2 text-[10px] text-stone-600"><ShieldCheck size={13}/>{es?'Identidad protegida por Firebase Authentication':'Identity protected by Firebase Authentication'}</div></section></main>;
};